version: "3.1"

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: point3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    ports:
      - 8080:8080